//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Course_CourseInfo
    {
        public int id { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> channelid { get; set; }
        public Nullable<int> sortid { get; set; }
        public string typelist { get; set; }
        public string teacherid { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> old_price { get; set; }
        public Nullable<double> memberpice { get; set; }
        public string content { get; set; }
        public string img { get; set; }
        public string attachid { get; set; }
        public Nullable<int> istop { get; set; }
        public Nullable<int> learns { get; set; }
        public string buys { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<System.DateTime> postdatetime { get; set; }
        public string favorites { get; set; }
        public Nullable<int> status { get; set; }
    }
}
