//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Course_VideoInfo
    {
        public int id { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> chapterid { get; set; }
        public string name { get; set; }
        public string videofile { get; set; }
        public string img { get; set; }
        public Nullable<int> videotime { get; set; }
        public string attachid { get; set; }
        public Nullable<System.DateTime> postdatetime { get; set; }
        public Nullable<int> display { get; set; }
        public string studys { get; set; }
        public Nullable<int> status { get; set; }
    }
}
