//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Exam_ExamLogInfo
    {
        public int id { get; set; }
        public Nullable<int> sortid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> channelid { get; set; }
        public Nullable<int> answers { get; set; }
        public string qidlist { get; set; }
        public string answerlist { get; set; }
        public string scorelist { get; set; }
        public Nullable<int> wrongs { get; set; }
        public Nullable<int> curwrongs { get; set; }
        public string wronglist { get; set; }
        public Nullable<int> notes { get; set; }
        public Nullable<int> curnotes { get; set; }
        public string notelist { get; set; }
        public Nullable<int> favs { get; set; }
        public Nullable<int> curfavs { get; set; }
        public string favlist { get; set; }
    }
}
