//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Exam_ExpInfo
    {
        public int id { get; set; }
        public Nullable<int> examid { get; set; }
        public Nullable<int> scorelower { get; set; }
        public Nullable<int> scoreupper { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<int> credits { get; set; }
        public string comment { get; set; }
    }
}
