//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Exam_SortQuestion
    {
        public int id { get; set; }
        public Nullable<int> channelid { get; set; }
        public Nullable<int> sortid { get; set; }
        public string type { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> counts { get; set; }
        public string questionlist { get; set; }
    }
}
