//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Exam_ExamQuestion
    {
        public int id { get; set; }
        public string kid { get; set; }
        public string parentid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> channelid { get; set; }
        public Nullable<int> sortid { get; set; }
        public string typelist { get; set; }
        public string type { get; set; }
        public Nullable<int> display { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string answer { get; set; }
        public Nullable<int> upperflg { get; set; }
        public Nullable<int> orderflg { get; set; }
        public string answerkey { get; set; }
        public Nullable<int> ascount { get; set; }
        public string explain { get; set; }
        public Nullable<int> difficulty { get; set; }
        public Nullable<System.DateTime> postdatetime { get; set; }
        public string attachid { get; set; }
        public Nullable<int> exams { get; set; }
        public Nullable<int> wrongs { get; set; }
        public Nullable<int> status { get; set; }
    }
}
