//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FP_ExamEntities : DbContext
    {
        public FP_ExamEntities()
            : base("name=FP_ExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FP_Course_ChapterInfo> FP_Course_ChapterInfo { get; set; }
        public virtual DbSet<FP_Course_CourseInfo> FP_Course_CourseInfo { get; set; }
        public virtual DbSet<FP_Course_VideoInfo> FP_Course_VideoInfo { get; set; }
        public virtual DbSet<FP_Exam_ExamInfo> FP_Exam_ExamInfo { get; set; }
        public virtual DbSet<FP_Exam_ExamLogInfo> FP_Exam_ExamLogInfo { get; set; }
        public virtual DbSet<FP_Exam_ExamNote> FP_Exam_ExamNote { get; set; }
        public virtual DbSet<FP_Exam_ExamQuestion> FP_Exam_ExamQuestion { get; set; }
        public virtual DbSet<FP_Exam_ExamResult> FP_Exam_ExamResult { get; set; }
        public virtual DbSet<FP_Exam_ExamResultTopic> FP_Exam_ExamResultTopic { get; set; }
        public virtual DbSet<FP_Exam_ExamSignInfo> FP_Exam_ExamSignInfo { get; set; }
        public virtual DbSet<FP_Exam_ExamTopic> FP_Exam_ExamTopic { get; set; }
        public virtual DbSet<FP_Exam_ExpInfo> FP_Exam_ExpInfo { get; set; }
        public virtual DbSet<FP_Exam_SortQuestion> FP_Exam_SortQuestion { get; set; }
        public virtual DbSet<FP_Exam_TestInfo> FP_Exam_TestInfo { get; set; }
        public virtual DbSet<FP_Exam_TestResult> FP_Exam_TestResult { get; set; }
        public virtual DbSet<FP_WMS_AttachInfo> FP_WMS_AttachInfo { get; set; }
        public virtual DbSet<FP_WMS_AttachType> FP_WMS_AttachType { get; set; }
        public virtual DbSet<FP_WMS_CacheInfo> FP_WMS_CacheInfo { get; set; }
        public virtual DbSet<FP_WMS_ChannelInfo> FP_WMS_ChannelInfo { get; set; }
        public virtual DbSet<FP_WMS_CreditInfo> FP_WMS_CreditInfo { get; set; }
        public virtual DbSet<FP_WMS_Department> FP_WMS_Department { get; set; }
        public virtual DbSet<FP_WMS_DesktopInfo> FP_WMS_DesktopInfo { get; set; }
        public virtual DbSet<FP_WMS_GradeInfo> FP_WMS_GradeInfo { get; set; }
        public virtual DbSet<FP_WMS_MenuInfo> FP_WMS_MenuInfo { get; set; }
        public virtual DbSet<FP_WMS_MsgTempInfo> FP_WMS_MsgTempInfo { get; set; }
        public virtual DbSet<FP_WMS_Permission> FP_WMS_Permission { get; set; }
        public virtual DbSet<FP_WMS_RoleInfo> FP_WMS_RoleInfo { get; set; }
        public virtual DbSet<FP_WMS_SessionInfo> FP_WMS_SessionInfo { get; set; }
        public virtual DbSet<FP_WMS_SortAppInfo> FP_WMS_SortAppInfo { get; set; }
        public virtual DbSet<FP_WMS_SortInfo> FP_WMS_SortInfo { get; set; }
        public virtual DbSet<FP_WMS_SysLogInfo> FP_WMS_SysLogInfo { get; set; }
        public virtual DbSet<FP_WMS_TaskInfo> FP_WMS_TaskInfo { get; set; }
        public virtual DbSet<FP_WMS_TypeInfo> FP_WMS_TypeInfo { get; set; }
        public virtual DbSet<FP_WMS_UserInfo> FP_WMS_UserInfo { get; set; }
    }
}
