//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Exam_ExamTopic
    {
        public int id { get; set; }
        public Nullable<int> examid { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public Nullable<int> display { get; set; }
        public Nullable<int> questions { get; set; }
        public Nullable<int> curquestions { get; set; }
        public string questionlist { get; set; }
        public Nullable<double> perscore { get; set; }
        public string randomsort { get; set; }
        public string randomcount { get; set; }
        public Nullable<int> randoms { get; set; }
        public Nullable<int> paper { get; set; }
    }
}
