//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Exam_ExamSignInfo
    {
        public int id { get; set; }
        public string ikey { get; set; }
        public Nullable<int> examid { get; set; }
        public Nullable<int> uid { get; set; }
        public string signer { get; set; }
        public string img { get; set; }
        public string payimg { get; set; }
        public string attachid { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> postdatetime { get; set; }
        public Nullable<int> status { get; set; }
    }
}
