//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Exam_ExamResult
    {
        public int id { get; set; }
        public Nullable<int> departid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> channelid { get; set; }
        public Nullable<int> sortid { get; set; }
        public Nullable<int> examid { get; set; }
        public string examname { get; set; }
        public Nullable<int> examtime { get; set; }
        public Nullable<int> examtype { get; set; }
        public Nullable<int> showanswer { get; set; }
        public Nullable<int> allowdelete { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> passmark { get; set; }
        public Nullable<double> score1 { get; set; }
        public Nullable<double> score2 { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<int> utime { get; set; }
        public Nullable<int> islimit { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<System.DateTime> examdatetime { get; set; }
        public Nullable<int> credits { get; set; }
        public Nullable<int> questions { get; set; }
        public Nullable<int> wrongs { get; set; }
        public Nullable<int> unanswer { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<int> getcredits { get; set; }
        public string exnote { get; set; }
        public string attachid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> paper { get; set; }
        public string ip { get; set; }
        public string mac { get; set; }
        public Nullable<int> isvideo { get; set; }
        public string client { get; set; }
        public Nullable<int> papertype { get; set; }
        public string title { get; set; }
        public string address { get; set; }
    }
}
