//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_Exam_ExamInfo
    {
        public int id { get; set; }
        public Nullable<int> departid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> channelid { get; set; }
        public Nullable<int> sortid { get; set; }
        public string typelist { get; set; }
        public string name { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> passmark { get; set; }
        public Nullable<int> examtime { get; set; }
        public Nullable<int> islimit { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<int> repeats { get; set; }
        public Nullable<int> showanswer { get; set; }
        public Nullable<int> allowdelete { get; set; }
        public Nullable<int> display { get; set; }
        public Nullable<System.DateTime> postdatetime { get; set; }
        public Nullable<int> examtype { get; set; }
        public string examroles { get; set; }
        public string examdeparts { get; set; }
        public string examuser { get; set; }
        public Nullable<int> credits { get; set; }
        public Nullable<int> exams { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<int> questions { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> papers { get; set; }
        public string title { get; set; }
        public string address { get; set; }
        public string opentime { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public Nullable<int> iscopy { get; set; }
        public Nullable<int> isvideo { get; set; }
        public Nullable<int> iswitch { get; set; }
        public Nullable<int> issign { get; set; }
        public string client { get; set; }
        public Nullable<int> papertype { get; set; }
    }
}
