//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_WMS_CreditInfo
    {
        public int id { get; set; }
        public Nullable<int> uid { get; set; }
        public string name { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> credits { get; set; }
        public Nullable<System.DateTime> postdatetime { get; set; }
        public Nullable<int> doid { get; set; }
        public string doname { get; set; }
    }
}
