//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_WMS_UserInfo
    {
        public int id { get; set; }
        public Nullable<int> roleid { get; set; }
        public string roles { get; set; }
        public Nullable<int> departid { get; set; }
        public string departname { get; set; }
        public string departlist { get; set; }
        public string departs { get; set; }
        public Nullable<int> display { get; set; }
        public Nullable<int> gradeid { get; set; }
        public string types { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string password2 { get; set; }
        public string email { get; set; }
        public Nullable<int> isemail { get; set; }
        public string mobile { get; set; }
        public Nullable<int> ismobile { get; set; }
        public string realname { get; set; }
        public string cardtype { get; set; }
        public string idcard { get; set; }
        public Nullable<int> isreal { get; set; }
        public string usercode { get; set; }
        public string nickname { get; set; }
        public string avatar { get; set; }
        public string sex { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<int> credits { get; set; }
        public string regip { get; set; }
        public Nullable<System.DateTime> joindatetime { get; set; }
        public Nullable<int> sumlogin { get; set; }
        public string lastip { get; set; }
        public Nullable<System.DateTime> lastvisit { get; set; }
        public string secques { get; set; }
        public string authstr { get; set; }
        public Nullable<System.DateTime> authtime { get; set; }
        public Nullable<int> authflag { get; set; }
        public string vipdate { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> issso { get; set; }
        public string extend { get; set; }
    }
}
