//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_WMS_SortInfo
    {
        public int id { get; set; }
        public Nullable<int> channelid { get; set; }
        public Nullable<int> appid { get; set; }
        public Nullable<int> display { get; set; }
        public Nullable<int> parentid { get; set; }
        public string parentlist { get; set; }
        public string name { get; set; }
        public string markup { get; set; }
        public Nullable<int> pagesize { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
        public string attach_icon { get; set; }
        public string img { get; set; }
        public string attach_img { get; set; }
        public Nullable<int> subcounts { get; set; }
        public string types { get; set; }
        public Nullable<int> showtype { get; set; }
        public string otherurl { get; set; }
        public Nullable<int> posts { get; set; }
    }
}
