//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_WMS_DesktopInfo
    {
        public int id { get; set; }
        public Nullable<int> uid { get; set; }
        public string app { get; set; }
        public Nullable<int> parentid { get; set; }
        public string name { get; set; }
        public string markup { get; set; }
        public string platform { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
        public string attach_icon { get; set; }
        public string url { get; set; }
        public string target { get; set; }
        public Nullable<int> desk { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> hidden { get; set; }
        public Nullable<int> display { get; set; }
    }
}
