//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_WMS_RoleInfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string markup { get; set; }
        public string description { get; set; }
        public string desktopurl { get; set; }
        public string sorts { get; set; }
        public string menus { get; set; }
        public string desktop { get; set; }
        public string permission { get; set; }
        public Nullable<int> isadmin { get; set; }
        public Nullable<int> isupload { get; set; }
        public Nullable<int> isdownload { get; set; }
        public Nullable<int> issms { get; set; }
    }
}
