//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_WMS_Permission
    {
        public int id { get; set; }
        public string name { get; set; }
        public string flagpage { get; set; }
        public Nullable<int> isadd { get; set; }
        public Nullable<int> isupdate { get; set; }
        public Nullable<int> isdelete { get; set; }
        public Nullable<int> isaudit { get; set; }
        public Nullable<int> status { get; set; }
    }
}
