//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_WMS_SessionInfo
    {
        public int id { get; set; }
        public string sid { get; set; }
        public Nullable<int> uid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string realname { get; set; }
        public string avatar { get; set; }
        public string platform { get; set; }
        public string token { get; set; }
        public string address { get; set; }
        public Nullable<int> roleid { get; set; }
        public string rolename { get; set; }
        public Nullable<int> departid { get; set; }
        public string departname { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<int> timeout { get; set; }
        public Nullable<int> invisible { get; set; }
        public Nullable<int> state { get; set; }
    }
}
