//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP_WMS_Department
    {
        public int id { get; set; }
        public string keyid { get; set; }
        public Nullable<int> parentid { get; set; }
        public string parentlist { get; set; }
        public string departlist { get; set; }
        public string name { get; set; }
        public string longname { get; set; }
        public string shortname { get; set; }
        public string markup { get; set; }
        public string types { get; set; }
        public string manager { get; set; }
        public string departer { get; set; }
        public Nullable<int> usercount { get; set; }
        public string description { get; set; }
        public Nullable<int> display { get; set; }
        public Nullable<int> subcounts { get; set; }
        public Nullable<int> posts { get; set; }
    }
}
